get:
  tags:
    - Wallets - MPC Wallets
  operationId: get_mpc_project_by_id
  summary: Get project information
  description: |
    This operation retrieves detailed information about a project.
  security:
    - CoboAuth: []
  parameters:
    - $ref: "../../../components/parameters/wallets/mpcs/project_id_path.yaml"
  responses:
    '200':
      $ref: "../../../components/responses/wallets/mpcs/get_project.yaml"
    '400':
      $ref: "../../../components/responses/errors/400_bad_request.yaml"
    '404':
      $ref: "../../../components/responses/errors/404_not_found.yaml"
    '503':
      $ref: "../../../components/responses/errors/503_service_unavailable.yaml"
put:
  tags:
    - Wallets - MPC Wallets
  operationId: update_mpc_project_by_id
  summary: Update project name
  description: |
    This operation updates a project's name.
  security:
    - CoboAuth: []
    - OAuth2:
        - mpc_user_controlled_project:manage
  parameters:
    - $ref: "../../../components/parameters/wallets/mpcs/project_id_path.yaml"
  requestBody:
    $ref: "../../../components/request_bodies/wallets/mpcs/update_project.yaml"
  responses:
    '200':
      $ref: "../../../components/responses/wallets/mpcs/get_project.yaml"
    '400':
      $ref: "../../../components/responses/errors/400_bad_request.yaml"
    '404':
      $ref: "../../../components/responses/errors/404_not_found.yaml"
    '503':
      $ref: "../../../components/responses/errors/503_service_unavailable.yaml"

